name: libp2p
description: A peer to peer library for MeshNote
version: 1.0.0
publish_to: none
#homepage: http://xxx.yyy.zzz

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  my_log:
    path: ../my_log

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
